name: maxradio # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: internet radio in tray # 79 char long summary
description: |
  This is internet radio

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  maxradio:
    command: bin/maxradio
    plugs:
    - unity7
    - network
    - network-bind
    - home
    - opengl
    - pulseaudio
    - mount-observe
    - optical-drive
    - camera
    - removable-media
    - screen-inhibit-control
    - x11
    - desktop
    - desktop-legacy
    - dvb
    - audio-playback
    - audio-record
    - jack1
    - avahi-control
    slots:
    - mpris
    - dbus-daemon

parts:
  maxradio:
    plugin: dump
    source: .
